export const ACTUALIZAR = "ACTUALIZAR";
export const ELIMINAR = "ELIMINAR";
export const ELIMINAR_OTRO = "ELIMINAR_OTRO";
export const OBTENER = "OBETENER";
export const OBTENER_LISTA = "OBETENER_LISTA";
export const OBTENER_LISTA_OTROS = "OBETENER_LISTA_OTROS";
export const OBTENER_LISTA_ACTIVAS = "OBETENER_LISTA_ACTIVAS";
export const OBTENER_LISTA_COMUNAS = "OBETENER_LISTA_COMUNAS";
export const OBTENER_LISTA_CARGOS = "OBETENER_LISTA_CARGOS";
export const OBTENER_LISTA_REGIONES = "OBETENER_LISTA_REGIONES";
export const OBTENER_LISTA_PAISES = "OBETENER_LISTA_PAISES";
export const OBTENER_LISTA_LUGAR_TRABAJO = "OBETENER_LISTA_LUGAR_TRABAJO";
export const OBTENER_LISTA_TIPO_LUGAR_TRABAJO = "OBETENER_LISTA_TIPO_LUGAR_TRABAJO";
export const OBTENER_LISTA_ZONAS = "OBETENER_LISTA_ZONAS";
export const OBTENER_LISTA_MODULOS = "OBTENER_LISTA_MODULOS";
export const OBTENER_LISTA_ROLES = "OBTENER_LISTA_ROLES";
export const OBTENER_LISTA_APLICACION = "OBTENER_LISTA_APLICACION"
export const OBTENER_LISTA_APLICACION_OEM = "OBTENER_LISTA_APLICACION_OEM";
export const OBTENER_LISTA_OEM = "OBTENER_LISTA_OEM";
export const OBTENER_LISTA_FLOTAS = "OBTENER_LISTA_FLOTAS";
export const OBTENER_LISTA_VERSION_EQUIPO = "OBTENER_LISTA_VERSION_EQUIPO";
export const OBTENER_MENU = "OBTENER_MENU";
export const OBTENER_ACCIONES = "OBTENER_ACCIONES";
export const REGISTRAR = "REGISTRAR";
export const REGISTRAR_OTRO = "REGISTRAR_OTRO";


